### ISSUE TITLE
spi4teensy3::release()

### ISSUE THREAD

**Issue by tinkerspy** [xxxajk/spi4teensy3#13]
The init() method seems to grab the SPI ports. I'm trying to write code that uses the SCK0 port after spi4teensy is done with it. I can't figure out how to undo whatever init() does.

So, any chance of a spi4teensy3::release() to match spi4teensy3::init()?

**Comment by xxxajk** [comment]
Simple...
```
CORE_PIN13_CONFIG = PORT_PCR_DSE | PORT_PCR_MUX(1);
/* Your code */
CORE_PIN13_CONFIG = PORT_PCR_DSE | PORT_PCR_MUX(2);
```
Let me know if that works out for you.

**Comment by tinkerspy** [comment]
Simple indeed. Works fine. Thanks!
